import { Router, type Router as ExpressRouter } from 'express';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const router: ExpressRouter = Router();

// Vendored bundle (server/assets/…), regenerated by `pnpm --filter @norc/claude-worker bundle`.
// '../../assets/…' resolves the same from src/routes (dev) and dist/routes (built).
const WORKER_PATH = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../assets/norc-claude-worker.mjs',
);

// GET /api/worker — the self-contained norc-claude-worker bundle. The copy-paste
// invite prompt downloads this and runs it with `node`; the worker then self-registers.
router.get('/', (_req, res) => {
  try {
    const js = readFileSync(WORKER_PATH, 'utf8');
    res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
    res.send(js);
  } catch {
    res.status(500).json({ error: 'worker_unavailable', hint: 'Run: pnpm --filter @norc/claude-worker bundle' });
  }
});

export { router as workerRouter };
