import { execSync } from 'child_process';
import chalk from 'chalk';
import { readConfig } from '../lib/config.js';

function ok(label: string, detail?: string)   { console.log(chalk.green('  ✓') + ' ' + label + (detail ? chalk.dim(' · ' + detail) : '')); }
function warn(label: string, detail?: string) { console.log(chalk.yellow('  !') + ' ' + label + (detail ? chalk.dim(' · ' + detail) : '')); }
function fail(label: string, detail?: string) { console.log(chalk.red('  ✗') + ' ' + label + (detail ? chalk.dim(' · ' + detail) : '')); }

function hasCmd(c: string): boolean {
  try { execSync(`which ${c}`, { stdio: 'ignore' }); return true; }
  catch { return false; }
}

async function reachable(url: string): Promise<boolean> {
  try {
    const r = await fetch(url, { signal: AbortSignal.timeout(3000) });
    return r.ok;
  } catch { return false; }
}

export async function runDoctor(): Promise<void> {
  console.log('\n' + chalk.bold('NORC Doctor\n'));

  // Dependencies
  console.log(chalk.dim('Dependencies:'));
  hasCmd('docker')  ? ok('Docker')  : fail('Docker',  'not found — install at docker.com');
  (() => { try { execSync('docker compose version', { stdio: 'ignore' }); return true; } catch { return false; } })()
    ? ok('docker compose') : fail('docker compose', 'update Docker Desktop to v4+');
  hasCmd('claude')
    ? ok('Claude Code CLI') : warn('Claude Code CLI', 'optional — npm i -g @anthropic-ai/claude-code');

  // Config (~/.norc/config.json)
  console.log('\n' + chalk.dim('NORC config (~/.norc/config.json):'));
  const config = await readConfig();

  config.notionApiKey          ? ok('Notion API key') : fail('Notion API key', 'run `norc init`');
  config.notionWebhookSecret   ? ok('Webhook secret', 'generated by NORC') : fail('Webhook secret', 'run `norc init`');
  config.notionOrgDbId         ? ok('Org DB', config.notionOrgDbId.slice(0,8) + '...') : fail('Org DB', 'run `norc init`');
  config.notionTasksDbId       ? ok('Tasks DB', config.notionTasksDbId.slice(0,8) + '...') : fail('Tasks DB', 'run `norc init`');
  config.notionProjectsDbId    ? ok('Projects DB') : fail('Projects DB', 'run `norc init`');
  config.notionPipelineConfigDbId ? ok('Pipeline Config DB') : fail('Pipeline Config DB', 'run `norc init`');

  // .env infra
  console.log('\n' + chalk.dim('Infrastructure (.env):'));
  const publicUrl = process.env.NORC_PUBLIC_URL;
  publicUrl
    ? ok('NORC_PUBLIC_URL', publicUrl)
    : fail('NORC_PUBLIC_URL', 'missing in .env — webhooks will not work');

  // Services
  console.log('\n' + chalk.dim('Services:'));
  const engineUp    = await reachable('http://localhost:3001/health');
  const dashboardUp = await reachable('http://localhost:3000');

  engineUp    ? ok('NORC engine (:3001)', 'healthy')  : fail('NORC engine (:3001)',    'offline — run: docker compose up -d');
  dashboardUp ? ok('Dashboard (:3000)',   'healthy')  : fail('Dashboard (:3000)',      'offline — run: docker compose up -d');

  if (engineUp) {
    try {
      const data = await fetch('http://localhost:3001/health').then(r => r.json()) as any;
      data.redis === 'ok' ? ok('Redis', 'connected') : fail('Redis', 'connection issue');
    } catch { warn('Redis', 'could not verify'); }
  }

  const issues = [
    !config.notionApiKey, !config.notionWebhookSecret,
    !config.notionOrgDbId, !config.notionTasksDbId,
    !publicUrl, !engineUp,
  ].filter(Boolean).length;

  console.log('\n' + (issues === 0
    ? chalk.green('All checks passed.')
    : chalk.yellow(`${issues} issue${issues > 1 ? 's' : ''} found. Run \`norc init\` to resolve.`)
  ) + '\n');
}
